### ISSUE TITLE
Installation fails on older Mac OSX versions

### ISSUE THREAD

**Issue by ambrosejcarr** [fastobo/fastobo-py#144]
Hello, thank you for building this tool! Our [cellxgene](https://github.com/chanzuckerberg/cellxgene) application depends on `fastobo`, and we're running into issues when our users are attempting to install `cellxgene` on old versions of OS X (e.g. 10.12). That version does not ship with a rust compiler, so our installation fails.

Would you be able to build [wheels](https://www.python.org/dev/peps/pep-0427/) for older versions of OSX? We believe that should solve the issue we're seeing. The pypi standard appears to be to support versions from 10.9 to present. 

Thanks!

cc @mckinsel @maniarathi

**Comment by althonos** [comment]
Hi @ambrosejcarr ,

glad this library is of use to some people, I made it simple and easy-to-use to broaden the audience of ontology consumers :smiley: 

Currently I am building wheels for OSX using the default Travis-CI OSX image, which is Xcode 9.4.1 / macOS 10.13. I'll try to see if it's feasible to use the lowest available version , but I think it only supports macOS 10.11 onward.

Other option I'll try is to have a build script that downloads the Rust compiler locally if not available, so that users without a Rust compiler installed manually can still build from source on their local platform.

**Comment by althonos** [comment]
`v0.9.1` now builds the OSX wheels with XCode 7.3, which should increase support of older versions. I also updated the setup script so that, if a wheel cannot be found and compilation from source is attempted, a minimal Rust compiler is used if none is available on the host machine.

**Comment by ambrosejcarr** [comment]
Thank you! We'll update our dependencies, check that our user's
installation problems are resolved, and report back.

**Comment by mckinsel** [comment]
Just wanted to confirm that this resolved the issue for our user. Thanks very much for the super fast fix @althonos!

**Comment by althonos** [comment]
Great, thanks!
